#!/bin/bash

#
# bridge_switcher - script to switch bridge mode on/off
#                   (usually called from the WLANPi menu system)    
#
# Written by Nigel Bowden <wifinigel@gmail.com>.
#

NAME=bridge_switcher
DESC="Script to switch bridge mode on/off"
STATUS_FILE="/etc/wlanpi-state"
NETWORKD_DIR=/etc/systemd/network
CLASSIC_MODE_NETWORK_DIR=/etc/systemd/network.classic
BRIDGE_MODE_NETWORK_DIR=/etc/systemd/network.bridge

if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root" 
   exit 1
fi

###############################################################################
#
# Activate bridge mode:
#
# 1. Check we're in classic mode
# 2. Move classic mode networkd files back to own dir
# 3. Move bridge mode networkd files to live networkd dir
# 4. Reboot
#
###############################################################################

bridge_on () {
  
  # check what state the WLAN Pi is in
  PI_STATUS=`cat $STATUS_FILE | grep 'classic'` || true
  if  [ -z "$PI_STATUS" ]; then
     echo "Failed - WLAN Pi is not in classic mode."
     exit 1
  fi

  echo "Enabling Bridge mode..."

  # move classic mode network files to own networkd dir
  sudo mv "$NETWORKD_DIR/*.net*" $CLASSIC_MODE_NETWORK_DIR

  # move bridge mode files in to networkd dir
  sudo mv "$BRIDGE_MODE_NETWORK_DIR/*.net*" $NETWORKD_DIR 

  # Signal that bridge mode is active
  echo "bridge" > $STATUS_FILE
  echo "WLAN Pi will now reboot to launch bridge mode."
  sleep 1
  reboot

}

###############################################################################
#
# De-activate bridge mode:
#
# 1. Check we're in bridge mode
# 2. Move bridge mode networkd files back to own dir
# 3. Move classic mode networkd files back live networkd dir
# 4. Reboot
#
###############################################################################

bridge_off () {

  # check what state the WLAN Pi is in
  PI_STATUS=`cat $STATUS_FILE | grep 'bridge'` || true
  if  [ -z "$PI_STATUS" ]; then
     echo "Failed - WLAN Pi is not in bridge mode."
     exit 1
  fi

  echo "Disabling bridge mode..."
  
  # move classic mode network files to own networkd dir
  sudo mv "$NETWORKD_DIR/*.net*" $BRIDGE_MODE_NETWORK_DIR

  # move bridge mode files in to networkd dir
  sudo mv "$CLASSIC_MODE_NETWORK_DIR/*.net*" $NETWORKD_DIR 

  echo "WLAN Pi will now reboot"
  echo "classic" > $STATUS_FILE
  sleep 1
  reboot

}


status () {

  PI_STATUS=`cat $STATUS_FILE | grep 'bridge'` || true
  if  [ -z "$PI_STATUS" ]; then
    echo "bridge mode is currently disabled"
    exit 0
  else
    echo "bridge mode is currently enabled"
    exit 0
  fi

}


case "$1" in
  on)
        bridge_on
        ;;
  off)
        bridge_off
        ;;
  status)
        status
        ;;
  *)
        N=/etc/wlanpi-bridge/$NAME
        echo "Usage: $N {on|off|status}" >&2
        exit 1
        ;;
esac

exit 0